// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RoastMySite.Infrastructure;

#nullable disable

namespace RoastMySite.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RoastMySite.Core.Entities.ScanReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CompletenessScore")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullReportJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<int>("LegalScore")
                        .HasColumnType("integer");

                    b.Property<string>("OverallGrade")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<int>("OverallScore")
                        .HasColumnType("integer");

                    b.Property<int>("PerformanceScore")
                        .HasColumnType("integer");

                    b.Property<string>("RoastSummary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("ScanRequestId")
                        .HasColumnType("uuid");

                    b.Property<int>("SeoScore")
                        .HasColumnType("integer");

                    b.Property<int>("TechScore")
                        .HasColumnType("integer");

                    b.Property<int>("TrustScore")
                        .HasColumnType("integer");

                    b.Property<int>("UxScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ScanRequestId")
                        .IsUnique();

                    b.ToTable("ScanReports");
                });

            modelBuilder.Entity("RoastMySite.Core.Entities.ScanRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BusinessType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TargetAudience")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.ToTable("ScanRequests");
                });

            modelBuilder.Entity("RoastMySite.Core.Entities.ScanReport", b =>
                {
                    b.HasOne("RoastMySite.Core.Entities.ScanRequest", "ScanRequest")
                        .WithOne("Report")
                        .HasForeignKey("RoastMySite.Core.Entities.ScanReport", "ScanRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanRequest");
                });

            modelBuilder.Entity("RoastMySite.Core.Entities.ScanRequest", b =>
                {
                    b.Navigation("Report");
                });
#pragma warning restore 612, 618
        }
    }
}
